package api
package main

import (
	"database/sql"
	"fmt"
	"log"
	"net/http"

























































































































































































































































































































































































































































































































































































































































































































}	c.JSON(http.StatusOK, transactions)	}		transactions = append(transactions, tx)		}			continue			log.Printf("Error scanning transaction: %v", err)		if err != nil {		)			&tx.CreatedAt,			&tx.Value, &tx.GasLimit, &tx.GasPrice, &tx.Nonce, &tx.Status, &tx.GasUsed,			&tx.TxHash, &tx.BlockNumber, &tx.TxIndex, &tx.FromAddress, &tx.ToAddress,		err := rows.Scan(		tx.ChainID = chainID		var tx Transaction	for rows.Next() {	transactions := []Transaction{}	defer rows.Close()	}		return		c.JSON(http.StatusInternalServerError, gin.H{"error": "Database error", "message": err.Error()})	if err != nil {	`, chainID, address, limit)		LIMIT $3		ORDER BY block_number DESC, tx_index		WHERE chain_id = $1 AND (from_address = $2 OR to_address = $2)		FROM transactions		       gas_limit, gas_price, nonce, status, gas_used, created_at		SELECT tx_hash, block_number, tx_index, from_address, to_address, value,	rows, err := api.db.Query(`	}		}			limit = parsedLimit		if parsedLimit, err := strconv.Atoi(l); err == nil && parsedLimit > 0 && parsedLimit <= 100 {	if l := c.Query("limit"); l != "" {	limit := 20		address := c.Param("address")	}		return		c.JSON(http.StatusBadRequest, gin.H{"error": "Invalid chain ID"})	if err != nil {	chainID, err := strconv.ParseInt(c.Param("chain_id"), 10, 64)func (api *API) handleGetAddressTransactions(c *gin.Context) {}	c.JSON(http.StatusOK, transactions)	}		transactions = append(transactions, tx)		}			continue			log.Printf("Error scanning transaction: %v", err)		if err != nil {		)			&tx.CreatedAt,			&tx.Value, &tx.GasLimit, &tx.GasPrice, &tx.Nonce, &tx.Status, &tx.GasUsed,			&tx.TxHash, &tx.BlockNumber, &tx.TxIndex, &tx.FromAddress, &tx.ToAddress,		err := rows.Scan(		tx.ChainID = chainID		var tx Transaction	for rows.Next() {	transactions := []Transaction{}	defer rows.Close()	}		return		c.JSON(http.StatusInternalServerError, gin.H{"error": "Database error", "message": err.Error()})	if err != nil {	`, chainID, blockNumber)		ORDER BY tx_index		WHERE chain_id = $1 AND block_number = $2		FROM transactions		       gas_limit, gas_price, nonce, status, gas_used, created_at		SELECT tx_hash, block_number, tx_index, from_address, to_address, value,	rows, err := api.db.Query(`	}		return		c.JSON(http.StatusBadRequest, gin.H{"error": "Invalid block number"})	if err != nil {	blockNumber, err := strconv.ParseInt(c.Param("block_number"), 10, 64)	}		return		c.JSON(http.StatusBadRequest, gin.H{"error": "Invalid chain ID"})	if err != nil {	chainID, err := strconv.ParseInt(c.Param("chain_id"), 10, 64)func (api *API) handleGetBlockTransactions(c *gin.Context) {}	c.JSON(http.StatusOK, tx)	}		return		c.JSON(http.StatusInternalServerError, gin.H{"error": "Database error", "message": err.Error()})	if err != nil {	}		return		c.JSON(http.StatusNotFound, gin.H{"error": "Transaction not found"})	if err == sql.ErrNoRows {	)		&tx.Status, &tx.GasUsed, &tx.CreatedAt,		&tx.Value, &tx.GasLimit, &tx.GasPrice, &tx.InputData, &tx.Nonce,		&tx.TxHash, &tx.BlockNumber, &tx.TxIndex, &tx.FromAddress, &tx.ToAddress,	`, chainID, txHash).Scan(		WHERE chain_id = $1 AND tx_hash = $2		FROM transactions		       gas_limit, gas_price, input_data, nonce, status, gas_used, created_at		SELECT tx_hash, block_number, tx_index, from_address, to_address, value,	err = api.db.QueryRow(`	tx.ChainID = chainID	var tx Transaction	txHash := c.Param("tx_hash")	}		return		c.JSON(http.StatusBadRequest, gin.H{"error": "Invalid chain ID"})	if err != nil {	chainID, err := strconv.ParseInt(c.Param("chain_id"), 10, 64)func (api *API) handleGetTransaction(c *gin.Context) {}	c.JSON(http.StatusOK, transactions)	}		transactions = append(transactions, tx)		}			continue			log.Printf("Error scanning transaction: %v", err)		if err != nil {		)			&tx.CreatedAt,			&tx.Value, &tx.GasLimit, &tx.GasPrice, &tx.Nonce, &tx.Status, &tx.GasUsed,			&tx.TxHash, &tx.BlockNumber, &tx.TxIndex, &tx.FromAddress, &tx.ToAddress,		err := rows.Scan(		tx.ChainID = chainID		var tx Transaction	for rows.Next() {	transactions := []Transaction{}	defer rows.Close()	}		return		c.JSON(http.StatusInternalServerError, gin.H{"error": "Database error", "message": err.Error()})	if err != nil {	`, chainID, limit)		LIMIT $2		ORDER BY block_number DESC, tx_index		WHERE chain_id = $1		FROM transactions		       gas_limit, gas_price, nonce, status, gas_used, created_at		SELECT tx_hash, block_number, tx_index, from_address, to_address, value,	rows, err := api.db.Query(`	}		}			limit = parsedLimit		if parsedLimit, err := strconv.Atoi(l); err == nil && parsedLimit > 0 && parsedLimit <= 100 {	if l := c.Query("limit"); l != "" {	limit := 20	}		return		c.JSON(http.StatusBadRequest, gin.H{"error": "Invalid chain ID"})	if err != nil {	chainID, err := strconv.ParseInt(c.Param("chain_id"), 10, 64)func (api *API) handleGetTransactions(c *gin.Context) {// ============================================================================// Transaction Handlers// ============================================================================}	c.JSON(http.StatusOK, block)	}		return		c.JSON(http.StatusInternalServerError, gin.H{"error": "Database error", "message": err.Error()})	if err != nil {	}		return		c.JSON(http.StatusNotFound, gin.H{"error": "Block not found"})	if err == sql.ErrNoRows {	)		&block.CreatedAt,		&block.GasUsed, &block.GasLimit, &block.BaseFeePerGas, &block.TransactionCount,		&block.BlockNumber, &block.BlockHash, &block.ParentHash, &block.Timestamp,	`, chainID, blockNumber).Scan(		WHERE chain_id = $1 AND block_number = $2		FROM blocks		       base_fee_per_gas, transaction_count, created_at		SELECT block_number, block_hash, parent_hash, timestamp, gas_used, gas_limit,	err = api.db.QueryRow(`	block.ChainID = chainID	var block Block	}		return		c.JSON(http.StatusBadRequest, gin.H{"error": "Invalid block number"})	if err != nil {	blockNumber, err := strconv.ParseInt(c.Param("block_number"), 10, 64)	}		return		c.JSON(http.StatusBadRequest, gin.H{"error": "Invalid chain ID"})	if err != nil {	chainID, err := strconv.ParseInt(c.Param("chain_id"), 10, 64)func (api *API) handleGetBlock(c *gin.Context) {}	c.JSON(http.StatusOK, blocks)	}		blocks = append(blocks, block)		}			continue			log.Printf("Error scanning block: %v", err)		if err != nil {		)			&block.CreatedAt,			&block.GasUsed, &block.GasLimit, &block.BaseFeePerGas, &block.TransactionCount,			&block.BlockNumber, &block.BlockHash, &block.ParentHash, &block.Timestamp,		err := rows.Scan(		block.ChainID = chainID		var block Block	for rows.Next() {	blocks := []Block{}	defer rows.Close()	}		return		c.JSON(http.StatusInternalServerError, gin.H{"error": "Database error", "message": err.Error()})	if err != nil {	`, chainID, limit)		LIMIT $2		ORDER BY block_number DESC		WHERE chain_id = $1		FROM blocks		       base_fee_per_gas, transaction_count, created_at		SELECT block_number, block_hash, parent_hash, timestamp, gas_used, gas_limit,	rows, err := api.db.Query(`	}		}			limit = parsedLimit		if parsedLimit, err := strconv.Atoi(l); err == nil && parsedLimit > 0 && parsedLimit <= 100 {	if l := c.Query("limit"); l != "" {	limit := 20	}		return		c.JSON(http.StatusBadRequest, gin.H{"error": "Invalid chain ID"})	if err != nil {	chainID, err := strconv.ParseInt(c.Param("chain_id"), 10, 64)func (api *API) handleGetBlocks(c *gin.Context) {// ============================================================================// Block Handlers// ============================================================================}	c.JSON(http.StatusOK, stats)	}		return		c.JSON(http.StatusInternalServerError, gin.H{"error": "Database error", "message": err.Error()})	if err != nil {	}		return		c.JSON(http.StatusNotFound, gin.H{"error": "Chain not found"})	if err == sql.ErrNoRows {	)		&stats.LastProcessed, &stats.AvgBlockTime, &stats.AvgTxsPerBlock,		&stats.ChainID, &stats.Name, &stats.TotalBlocks, &stats.TotalTxs,	`, chainID).Scan(		GROUP BY c.chain_id, c.name, cp.last_processed_block		WHERE c.chain_id = $1		LEFT JOIN checkpoints cp ON c.chain_id = cp.chain_id AND cp.service_name = 'ingester'		LEFT JOIN transactions t ON c.chain_id = t.chain_id		LEFT JOIN blocks b2 ON c.chain_id = b2.chain_id AND b2.block_number = b.block_number + 1		LEFT JOIN blocks b ON c.chain_id = b.chain_id		FROM chains c			AVG(b.transaction_count) as avg_txs_per_block			AVG(EXTRACT(EPOCH FROM (b2.timestamp - b.timestamp))) as avg_block_time,			cp.last_processed_block,			COUNT(t.tx_hash) as total_txs,			COUNT(DISTINCT b.block_number) as total_blocks,			c.name,			c.chain_id,		SELECT 	err = api.db.QueryRow(`	var stats ChainStats	}		return		c.JSON(http.StatusBadRequest, gin.H{"error": "Invalid chain ID"})	if err != nil {	chainID, err := strconv.ParseInt(c.Param("chain_id"), 10, 64)func (api *API) handleGetChainStats(c *gin.Context) {}	c.JSON(http.StatusOK, chain)	}		return		c.JSON(http.StatusInternalServerError, gin.H{"error": "Database error", "message": err.Error()})	if err != nil {	}		return		c.JSON(http.StatusNotFound, gin.H{"error": "Chain not found"})	if err == sql.ErrNoRows {	`, chainID).Scan(&chain.ChainID, &chain.Name, &chain.IsActive, &chain.CreatedAt, &chain.UpdatedAt)		WHERE chain_id = $1		FROM chains		SELECT chain_id, name, is_active, created_at, updated_at	err = api.db.QueryRow(`	var chain Chain	}		return		c.JSON(http.StatusBadRequest, gin.H{"error": "Invalid chain ID"})	if err != nil {	chainID, err := strconv.ParseInt(c.Param("chain_id"), 10, 64)func (api *API) handleGetChain(c *gin.Context) {}	c.JSON(http.StatusOK, chains)	}		chains = append(chains, chain)		}			continue			log.Printf("Error scanning chain: %v", err)		if err != nil {		)			&chain.CreatedAt, &chain.UpdatedAt,			&chain.LastBlock, &chain.BlockCount, &chain.TxCount,			&chain.ChainID, &chain.Name, &chain.IsActive,		err := rows.Scan(		var chain Chain	for rows.Next() {	chains := []Chain{}	defer rows.Close()	}		return		c.JSON(http.StatusInternalServerError, gin.H{"error": "Database query failed", "message": err.Error()})	if err != nil {	rows, err := api.db.Query(query)	`		ORDER BY c.chain_id		GROUP BY c.chain_id, c.name, c.is_active, cp.last_processed_block, c.created_at, c.updated_at		WHERE c.is_active = true		LEFT JOIN transactions t ON c.chain_id = t.chain_id		LEFT JOIN blocks b ON c.chain_id = b.chain_id		LEFT JOIN checkpoints cp ON c.chain_id = cp.chain_id AND cp.service_name = 'ingester'		FROM chains c			c.created_at, c.updated_at			COUNT(t.tx_hash) as tx_count,			COUNT(DISTINCT b.block_number) as block_count,			cp.last_processed_block,			c.chain_id, c.name, c.is_active,		SELECT 	query := `func (api *API) handleGetChains(c *gin.Context) {// ============================================================================// Chain Handlers// ============================================================================}	c.Data(http.StatusOK, "text/html; charset=utf-8", []byte(docs))`</html></body>}</pre>  "message": "Block 123 not found on chain 1"  "error": "Not found",    <pre>{    <p>All responses are JSON. Errors return appropriate HTTP status codes with error messages.</p>    <h2>Response Format</h2>        </ul>        <li><strong>8453</strong> - Base</li>        <li><strong>10</strong> - Optimism</li>        <li><strong>42161</strong> - Arbitrum One</li>        <li><strong>137</strong> - Polygon</li>        <li><strong>1</strong> - Ethereum Mainnet</li>    <ul>    <h2>Chain IDs</h2>        </div>        <pre>curl http://localhost:8000/api/v1/chains/1/addresses/0xabc.../transactions?limit=50</pre>        <p>Get transactions for an address. Query params: <code>limit</code> (default 20, max 100)</p>        <strong>/chains/:chain_id/addresses/:address/transactions</strong>        <span class="method get">GET</span>    <div class="endpoint">        </div>        <pre>curl http://localhost:8000/api/v1/chains/1/transactions/0x123...</pre>        <p>Get a specific transaction by hash</p>        <strong>/chains/:chain_id/transactions/:tx_hash</strong>        <span class="method get">GET</span>    <div class="endpoint">        </div>        <pre>curl http://localhost:8000/api/v1/chains/1/blocks/18500000/transactions</pre>        <p>Get all transactions in a block</p>        <strong>/chains/:chain_id/blocks/:block_number/transactions</strong>        <span class="method get">GET</span>    <div class="endpoint">        </div>        <pre>curl http://localhost:8000/api/v1/chains/1/blocks/18500000</pre>        <p>Get a specific block by number</p>        <strong>/chains/:chain_id/blocks/:block_number</strong>        <span class="method get">GET</span>    <div class="endpoint">        </div>        <pre>curl http://localhost:8000/api/v1/chains/1/blocks?limit=10</pre>        <p>Get recent blocks. Query params: <code>limit</code> (default 20, max 100)</p>        <strong>/chains/:chain_id/blocks</strong>        <span class="method get">GET</span>    <div class="endpoint">        </div>        <pre>curl http://localhost:8000/api/v1/chains/1/stats</pre>        <p>Get statistics for a chain (total blocks, transactions, averages)</p>        <strong>/chains/:chain_id/stats</strong>        <span class="method get">GET</span>    <div class="endpoint">        </div>        <pre>curl http://localhost:8000/api/v1/chains/1</pre>        <p>Get details for a specific chain (1=Ethereum, 137=Polygon, etc.)</p>        <strong>/chains/:chain_id</strong>        <span class="method get">GET</span>    <div class="endpoint">        </div>        <pre>curl http://localhost:8000/api/v1/chains</pre>        <p>List all supported chains with statistics</p>        <strong>/chains</strong>        <span class="method get">GET</span>    <div class="endpoint">        <h2>Endpoints</h2>        <code>http://localhost:8000/api/v1</code>    <h2>Base URL</h2>        <p>Multi-chain blockchain data API supporting Ethereum, Polygon, Arbitrum, Optimism, and Base.</p>    <h1>🚀 Blockchain Indexer API</h1><body></head>    </style>        pre { background: #282c34; color: #abb2bf; padding: 15px; border-radius: 5px; overflow-x: auto; }        code { background: #f4f4f4; padding: 2px 6px; border-radius: 3px; }        .get { background: #61affe; color: white; }        .method { display: inline-block; padding: 4px 8px; border-radius: 4px; font-weight: bold; margin-right: 10px; }        .endpoint { background: #f8f9fa; padding: 15px; margin: 10px 0; border-left: 4px solid #3498db; }        h2 { color: #34495e; border-bottom: 2px solid #3498db; padding-bottom: 10px; margin-top: 40px; }        h1 { color: #2c3e50; }        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 1200px; margin: 40px auto; padding: 0 20px; }    <style>    <title>Blockchain Indexer API</title><head><html><!DOCTYPE html>	docs := `func (api *API) handleDocs(c *gin.Context) {}	})		Chains:    chains,		Database:  dbStatus,		Timestamp: time.Now(),		Status:    "healthy",	c.JSON(http.StatusOK, HealthResponse{	}		}			}				}					chains[name] = "not started"				} else {					chains[name] = fmt.Sprintf("block %d", *lastBlock)				if lastBlock != nil {			if err := rows.Scan(&chainID, &name, &lastBlock); err == nil {			var lastBlock *int64			var name string			var chainID int64		for rows.Next() {		defer rows.Close()	if err == nil {	`)		WHERE c.is_active = true		LEFT JOIN checkpoints cp ON c.chain_id = cp.chain_id AND cp.service_name = 'ingester'		FROM chains c		SELECT c.chain_id, c.name, cp.last_processed_block	rows, err := api.db.Query(`	chains := make(map[string]string)	// Check chains	}		dbStatus = "error: " + err.Error()	if err := api.db.Ping(); err != nil {	dbStatus := "ok"	// Check databasefunc (api *API) handleHealth(c *gin.Context) {// ============================================================================// Health & Docs// ============================================================================}	}		v1.GET("/chains/:chain_id/addresses/:address/transactions", api.handleGetAddressTransactions)		// Address				v1.GET("/chains/:chain_id/blocks/:block_number/transactions", api.handleGetBlockTransactions)		v1.GET("/chains/:chain_id/transactions/:tx_hash", api.handleGetTransaction)		v1.GET("/chains/:chain_id/transactions", api.handleGetTransactions)		// Transactions				v1.GET("/chains/:chain_id/blocks/:block_number", api.handleGetBlock)		v1.GET("/chains/:chain_id/blocks", api.handleGetBlocks)		// Blocks				v1.GET("/chains/:chain_id/stats", api.handleGetChainStats)		v1.GET("/chains/:chain_id", api.handleGetChain)		v1.GET("/chains", api.handleGetChains)		// Chains	{	v1 := api.router.Group("/api/v1")	// V1 API routes		api.router.GET("/docs", api.handleDocs)	// API documentation		api.router.GET("/health", api.handleHealth)	// Health check	api.router.Use(cors.New(config))	config.AllowHeaders = []string{"Origin", "Content-Type"}	config.AllowMethods = []string{"GET", "OPTIONS"}	config.AllowOrigins = []string{"*"} // For development; restrict in production	config := cors.DefaultConfig()	// CORS configurationfunc (api *API) setupRoutes() {}	return db, nil	}		return nil, fmt.Errorf("failed to ping database: %w", err)	if err := db.Ping(); err != nil {	db.SetConnMaxLifetime(5 * time.Minute)	db.SetMaxIdleConns(10)	db.SetMaxOpenConns(25)	}		return nil, fmt.Errorf("failed to open database: %w", err)	if err != nil {	db, err := sql.Open("postgres", dbURL)	}		dbURL = "postgres://indexer:indexer_password@localhost:5432/blockchain_indexer?sslmode=disable"	if dbURL == "" {	dbURL := os.Getenv("DATABASE_URL")func connectDB() (*sql.DB, error) {}	}		log.Fatalf("❌ Failed to start server: %v", err)	if err := api.router.Run(":" + port); err != nil {		log.Printf("💚 Health check: http://localhost:%s/health", port)	log.Printf("📖 Documentation: http://localhost:%s/docs", port)	log.Printf("🌐 API server starting on port %s", port)	}		port = "8000"	if port == "" {	port := os.Getenv("API_PORT")	// Start server	api.setupRoutes()	// Setup routes	}		router: gin.Default(),		db:     db,	api := &API{	// Initialize API	log.Println("✅ Database connected")	defer db.Close()	}		log.Fatalf("❌ Database connection failed: %v", err)	if err != nil {	db, err := connectDB()	// Connect to database	log.Println("🚀 Starting Blockchain Indexer API")	log.SetFlags(log.LstdFlags | log.Lshortfile)func main() {}	Chains    map[string]string `json:"chains"`	Database  string            `json:"database"`	Timestamp time.Time         `json:"timestamp"`	Status    string            `json:"status"`type HealthResponse struct {}	AvgTxsPerBlock  *float64 `json:"avg_txs_per_block,omitempty"`	AvgBlockTime    *float64 `json:"avg_block_time_seconds,omitempty"`	LastProcessed   *int64 `json:"last_processed_block,omitempty"`	TotalTxs        int64  `json:"total_transactions"`	TotalBlocks     int64  `json:"total_blocks"`	Name            string `json:"name"`	ChainID         int64  `json:"chain_id"`type ChainStats struct {}	CreatedAt   time.Time `json:"created_at"`	GasUsed     int64     `json:"gas_used"`	Status      int       `json:"status"`	Nonce       int64     `json:"nonce"`	InputData   []byte    `json:"input_data,omitempty"`	GasPrice    string    `json:"gas_price"`	GasLimit    int64     `json:"gas_limit"`	Value       string    `json:"value"`	ToAddress   *string   `json:"to_address,omitempty"`	FromAddress string    `json:"from_address"`	TxIndex     int       `json:"tx_index"`	BlockNumber int64     `json:"block_number"`	TxHash      string    `json:"tx_hash"`	ChainID     int64     `json:"chain_id"`type Transaction struct {}	CreatedAt       time.Time `json:"created_at"`	TransactionCount int      `json:"transaction_count"`	BaseFeePerGas   *string   `json:"base_fee_per_gas,omitempty"`	GasLimit        int64     `json:"gas_limit"`	GasUsed         int64     `json:"gas_used"`	Timestamp       time.Time `json:"timestamp"`	ParentHash      string    `json:"parent_hash"`	BlockHash       string    `json:"block_hash"`	BlockNumber     int64     `json:"block_number"`	ChainID         int64     `json:"chain_id"`type Block struct {}	UpdatedAt   time.Time `json:"updated_at"`	CreatedAt   time.Time `json:"created_at"`	TxCount     *int64    `json:"tx_count,omitempty"`	BlockCount  *int64    `json:"block_count,omitempty"`	LastBlock   *int64    `json:"last_block,omitempty"`	IsActive    bool      `json:"is_active"`	Name        string    `json:"name"`	ChainID     int64     `json:"chain_id"`type Chain struct {// Response types}	router *gin.Engine	db     *sql.DBtype API struct {)	_ "github.com/lib/pq"	"github.com/gin-gonic/gin"	"github.com/gin-contrib/cors"	"time"	"strconv"	"os"