package scripts
package main

import (
	"context"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"log"
	"math/big"
	"os"
	"strings"

	"github.com/ethereum/go-ethereum"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core/types"
	"github.com/ethereum/go-ethereum/ethclient"
	"github.com/ethereum/go-ethereum/rpc"
)

// Known transaction hashes to explore (replace with real ones)
var exploreTxs = map[string]string{
	"uniswap_v2_swap":    "0x5c504ed432cb51138bcf09aa5e8a410dd4a1e204ef84bfed1be16dfba1b22060", // Example - replace with real
	"uniswap_v3_swap":    "",
	"layerzero_bridge":   "",
	"failed_transaction": "",
}

















































































































































































































































































}	return nil	}		}			log.Printf("Decoded Reason: %s", strings.TrimSpace(reason))			reason := strings.TrimPrefix(err.Error(), "execution reverted:")		if strings.Contains(err.Error(), "execution reverted:") {		// Try to decode if it's a string				log.Printf("Revert Reason: %v", err)		// The error message contains the revert reason	if err != nil {	_, err = client.CallContract(ctx, msg, receipt.BlockNumber)	}		Data:     tx.Data(),		Value:    tx.Value(),		GasPrice: tx.GasPrice(),		Gas:      tx.Gas(),		To:       tx.To(),		From:     from,	msg := ethereum.CallMsg{	from, _ := types.Sender(types.LatestSignerForChainID(tx.ChainId()), tx)	// Replay with eth_call to get revert reason	}		return fmt.Errorf("failed to get transaction: %w", err)	if err != nil {	tx, _, err := client.TransactionByHash(ctx, txHash)	// Get the transaction	log.Println("Transaction failed - attempting to extract revert reason")	}		return nil		log.Println("Transaction succeeded - no revert")	if receipt.Status == 1 {	}		return fmt.Errorf("failed to get receipt: %w", err)	if err != nil {	receipt, err := client.TransactionReceipt(ctx, txHash)	log.Println("\n❌ === REVERT REASON EXTRACTION ===")func exploreRevertReason(ctx context.Context, client *ethclient.Client, txHash common.Hash) error {// Additional helper: Test revert reason extraction}	}		log.Printf("  ✅ KNOWN EVENT: %s", name)	if name, ok := events[sig]; ok {	}		"0xc42079f94a6350d7e6235f29174924f928cc2ac818eb64fed8004e115fbcca67": "Swap (Uniswap V3)",		"0xc3d58168c5ae7397731d063d5bbf3d657854427343f4c083240f7aacaa2d0f62": "Swap (Uniswap V2)",		"0x8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925": "Approval (ERC20)",		"0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef": "Transfer (ERC20/ERC721)",	events := map[string]string{func checkKnownEventSignature(sig string) {}	}		log.Printf("❓ Unknown signature - look up at https://www.4byte.directory/signatures/?bytes4_signature=%s", sig)	} else {		log.Printf("✅ KNOWN: %s", name)	if name, ok := signatures[sig]; ok {	}		"0x42842e0e": "safeTransferFrom (ERC721)",		"0x095ea7b3": "approve (ERC20)",		"0x23b872dd": "transferFrom (ERC20)",		"0xa9059cbb": "transfer (ERC20)",		"0xc04b8d59": "exactInput (Uniswap V3)",		"0x414bf389": "exactInputSingle (Uniswap V3)",		"0x18cbafe5": "swapExactTokensForETH (Uniswap V2)",		"0x7ff36ab5": "swapExactETHForTokens (Uniswap V2)",		"0x38ed1739": "swapExactTokensForTokens (Uniswap V2)",	signatures := map[string]string{func checkKnownSignature(sig string) {}	return from.Hex()	}		return "unknown"	if err != nil {	from, err := types.Sender(types.LatestSignerForChainID(tx.ChainId()), tx)	// For production, use types.Sender() with proper signer	// Note: This requires the chain ID to recover senderfunc getSender(tx *types.Transaction) string {}	return nil	}		log.Printf("✅ trace_transaction works!")	} else {		log.Printf("❌ trace_transaction not supported: %v", err)	if err != nil {	err = rpcClient.CallContext(ctx, &traceResult2, "trace_transaction", txHash)	var traceResult2 interface{}	// Try trace_transaction (OpenEthereum/Erigon)	}		log.Printf("Trace result:\n%s", string(traceJSON))		traceJSON, _ := json.MarshalIndent(traceResult, "", "  ")		log.Printf("✅ debug_traceTransaction works!")	} else {		log.Printf("   Alternatives: Use trace_transaction or parity_trace")		log.Printf("   Note: This requires an archive node with debug APIs enabled")		log.Printf("❌ debug_traceTransaction not supported or tx not found: %v", err)	if err != nil {	})		"tracer": "callTracer",	err = rpcClient.CallContext(ctx, &traceResult, "debug_traceTransaction", txHash, map[string]interface{}{	var traceResult interface{}	// Try debug_traceTransaction	log.Printf("Attempting to trace tx: %s", txHash)	log.Printf("⚠️  Testing trace methods (may not be supported by all RPC providers)")	txHash := "0x1234567890123456789012345678901234567890123456789012345678901234"	// Example transaction hash - replace with a real one that has internal txs	defer rpcClient.Close()	}		return fmt.Errorf("failed to connect to RPC: %w", err)	if err != nil {	rpcClient, err := rpc.Dial(rpcURL)	// Use raw RPC client for debug/trace methods	log.Println("\n🔍 === INTERNAL TRANSACTION TRACING ===")func exploreInternalTransactions(ctx context.Context, rpcURL string) error {}	return nil	}		}			log.Printf("  Data: %d bytes", len(firstLog.Data))			log.Printf("  Topics: %d", len(firstLog.Topics))			}				checkKnownEventSignature(firstLog.Topics[0].Hex())				log.Printf("  Event Signature: %s", firstLog.Topics[0].Hex())			if len(firstLog.Topics) > 0 {			log.Printf("  Contract: %s", firstLog.Address.Hex())			firstLog := receipt.Logs[0]			log.Printf("\nFirst Event:")		if len(receipt.Logs) > 0 {		// Explore events		log.Printf("Logs/Events: %d", len(receipt.Logs))		log.Printf("Gas Used: %d", receipt.GasUsed)		log.Printf("Status: %d (1=success, 0=failed)", receipt.Status)		}			continue			log.Printf("Could not get receipt: %v", err)		if err != nil {		receipt, err := client.TransactionReceipt(ctx, tx.Hash())		// Get transaction receipt		}			log.Printf("Input Data: empty (simple transfer)")		} else {			log.Printf("Input Data: %s (not a function call)", hex.EncodeToString(data))		} else if len(data) > 0 {			checkKnownSignature(funcSig)			// Check if it matches known signatures			log.Printf("Input Data Length: %d bytes", len(data))			log.Printf("Function Signature: %s", funcSig)			funcSig := "0x" + hex.EncodeToString(data[:4])		if len(data) >= 4 {		data := tx.Data()		// Analyze input data		log.Printf("Gas Price: %s", tx.GasPrice().String())		log.Printf("Gas: %d", tx.Gas())		log.Printf("Value: %s wei", tx.Value().String())		}			log.Printf("To: nil (contract creation)")		} else {			log.Printf("To: %s", tx.To().Hex())		if tx.To() != nil {		log.Printf("From: %s", getSender(tx))		log.Printf("Hash: %s", tx.Hash().Hex())		log.Printf("\n--- Transaction %d ---", i+1)	for i, tx := range block.Transactions()[:count] {	}		count = len(block.Transactions())	if len(block.Transactions()) < count {	count := 3	// Explore first 3 transactions	log.Printf("Exploring block %d with %d transactions\n", block.Number().Uint64(), len(block.Transactions()))	}		return fmt.Errorf("failed to get block: %w", err)	if err != nil {	block, err := client.BlockByNumber(ctx, blockNumber)	blockNumber := big.NewInt(18500000) // Adjust to recent block	// Get a recent block with transactions	log.Println("\n💸 === TRANSACTION EXPLORATION ===")func exploreRecentTransactions(ctx context.Context, client *ethclient.Client) error {}	return nil	log.Printf("Miner: %s", block.Coinbase().Hex())	log.Printf("Transaction Count: %d", len(block.Transactions()))	}		return fmt.Errorf("failed to get full block: %w", err)	if err != nil {	block, err := client.BlockByNumber(ctx, header.Number)	// Get full block with transactions	log.Printf("Gas Limit: %d", header.GasLimit)	log.Printf("Gas Used: %d", header.GasUsed)	log.Printf("Timestamp: %d", header.Time)	log.Printf("Parent Hash: %s", header.ParentHash.Hex())	log.Printf("Block Hash: %s", header.Hash().Hex())	log.Printf("Block Number: %d", header.Number.Uint64())	}		return fmt.Errorf("failed to get latest header: %w", err)	if err != nil {	header, err := client.HeaderByNumber(ctx, nil)	log.Println("\n📦 === LATEST BLOCK EXPLORATION ===")func exploreLatestBlock(ctx context.Context, client *ethclient.Client) error {}	}		log.Printf("❌ Error exploring internal transactions: %v\n", err)	if err := exploreInternalTransactions(ctx, rpcURL); err != nil {	// Test internal transaction tracing	}		log.Printf("❌ Error exploring transactions: %v\n", err)	if err := exploreRecentTransactions(ctx, client); err != nil {	// Explore a recent block with transactions	}		log.Printf("❌ Error exploring latest block: %v\n", err)	if err := exploreLatestBlock(ctx, client); err != nil {	// Get latest block info	log.Println("✅ Connected to Ethereum RPC")	defer client.Close()	}		log.Fatalf("Failed to connect to Ethereum client: %v", err)	if err != nil {	client, err := ethclient.Dial(rpcURL)	// Connect to Ethereum client	ctx := context.Background()	}		os.Exit(1)		log.Println("   Get free API key from: https://www.alchemy.com/")		log.Println("⚠️  Using placeholder RPC URL. Set ETH_RPC_URL environment variable.")		rpcURL = "https://eth-mainnet.g.alchemy.com/v2/YOUR_API_KEY"	if rpcURL == "" {	rpcURL := os.Getenv("ETH_RPC_URL")	// Read RPC URL from environment or use defaultfunc main() {